plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.bbauu22.musicbu'
    compileSdk 34

    defaultConfig {
        applicationId 'dev.bbauu22.musicbu'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
