name: Rotate MP3 (No-Repeat Random) and Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - 'playlist.txt'
      - '.github/workflows/deploy.yml'
  schedule:
    - cron: "*/90 * * * *"  # đổi bài mỗi 90 phút (1h30)

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pick next track (random among unplayed)
        id: pick
        shell: bash
        run: |
          set -e

          # 1) Đọc playlist (lọc bỏ dòng trống)
          if [ ! -s playlist.txt ]; then
            echo "playlist.txt is empty or missing"; exit 1
          fi
          mapfile -t LINES < <(awk 'NF{print}' playlist.txt)
          TOTAL=${#LINES[@]}
          if [ "$TOTAL" -le 0 ]; then
            echo "No valid lines in playlist.txt"; exit 1
          fi

          # 2) Đọc danh sách đã phát (played.txt)
          declare -A USED
          if [ -f played.txt ]; then
            while IFS= read -r idx; do
              [[ "$idx" =~ ^[0-9]+$ ]] && USED[$idx]=1
            done < played.txt
          fi

          # 3) Tập các chỉ mục chưa phát
          avail=()
          for ((i=0;i<TOTAL;i++)); do
            if [ -z "${USED[$i]}" ]; then
              avail+=("$i")
            fi
          done

          # 4) Nếu đã phát hết -> reset vòng mới
          if [ "${#avail[@]}" -eq 0 ]; then
            echo "All tracks were played. Resetting..."
            : > played.txt   # clear file
            for ((i=0;i<TOTAL;i++)); do avail+=("$i"); done
          fi

          # 5) Random 1 chỉ mục trong 'avail'
          rnd=$(( RANDOM % ${#avail[@]} ))
          PICK=${avail[$rnd]}
          URL="${LINES[$PICK]}"

          echo "Picked index: $PICK"
          echo "URL: $URL"

          # Xuất cho step kế tiếp
          echo "index=$PICK" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Download MP3 to fixed link
        shell: bash
        run: |
          set -e
          mkdir -p public/f
          echo "Downloading: ${{ steps.pick.outputs.url }}"
          curl -L "${{ steps.pick.outputs.url }}" -o "public/f/xz8cvuf.mp3"

      - name: Update played list and commit
        shell: bash
        run: |
          set -e
          echo "${{ steps.pick.outputs.index }}" >> played.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add played.txt
          git commit -m "Played index ${{ steps.pick.outputs.index }}" || echo "No changes"
          git push || echo "No push needed"

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
