name: Rotate Link (rename current mp3)

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "File cần đổi (vd: f/xz8cvuf.mp3). Để trống sẽ chọn file mp3 đầu tiên trong f/"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Pick target
        id: pick
        run: |
          F="${{ github.event.inputs.filename }}"
          if [ -z "$F" ]; then
            F=$(ls -1 f/*.mp3 2>/dev/null | head -n1)
          fi
          if [ -z "$F" ]; then echo "No mp3 in f/"; exit 1; fi
          echo "target=$F" >> $GITHUB_OUTPUT

      - name: Generate new name & rename
        run: |
          NEW="f/$(python3 - <<'PY'
import secrets; print(secrets.token_hex(6)+".mp3")
PY
)"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git mv "${{ steps.pick.outputs.target }}" "$NEW"
          echo "$NEW" > f/current.txt
          git add -A
          git commit -m "Rotate link: ${{ steps.pick.outputs.target }} -> $NEW"
          git push
