name: Fetch & Rotate MP3 (HARDENED)

on:
  workflow_dispatch: {}   # chạy tay

permissions:
  contents: write

jobs:
  fetch_rotate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure folder f/
        run: mkdir -p f

      - name: Pick source URL (playlist.txt line 1, fallback source_url.txt)
        id: src
        shell: bash
        run: |
          set -e
          URL=""
          if [ -f playlist.txt ]; then
            URL=$(sed -n '1p' playlist.txt | tr -d '\r')
          fi
          if [ -z "$URL" ] && [ -f source_url.txt ]; then
            URL=$(sed -n '1p' source_url.txt | tr -d '\r')
          fi
          echo "URL=$URL"
          if [ -z "$URL" ]; then
            echo "::error::Không thấy URL trong playlist.txt / source_url.txt"; exit 1
          fi
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Show HTTP headers (CURL DEBUG)
        shell: bash
        run: |
          URL='${{ steps.src.outputs.url }}'
          echo "---- HEADERS ----"
          curl -I -L \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36" \
            -H "Referer: https://google.com" \
            "$URL" || true
          echo "------------------"

      - name: Download MP3 (robust)
        shell: bash
        run: |
          set -e
          URL='${{ steps.src.outputs.url }}'
          echo "Downloading: $URL"
          # Thử curl
          curl -L --retry 3 --connect-timeout 20 \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36" \
            -H "Referer: https://google.com" \
            "$URL" -o fetched.mp3 || true
          SZ=$(wc -c < fetched.mp3 2>/dev/null || echo 0)
          echo "Curl size: $SZ bytes"
          if [ "$SZ" -lt 10240 ]; then
            echo "Curl có thể thất bại; thử aria2c..."
            sudo apt-get update -y >/dev/null
            sudo apt-get install -y aria2 >/dev/null
            aria2c -x 8 -s 8 --timeout=20 --allow-overwrite=true \
              --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36" \
              --referer="https://google.com" \
              -o fetched.mp3 "$URL" || true
            SZ=$(wc -c < fetched.mp3 2>/dev/null || echo 0)
            echo "Aria2 size: $SZ bytes"
          fi
          if [ "$SZ" -lt 10240 ]; then
            echo "::error::Tải không thành công (file <10KB). Nhiều khả năng nguồn chặn GitHub hoặc URL lỗi."
            exit 1
          fi

      - name: Rotate link (random rename, remove old)
        env:
          GIT_COMMITTER_NAME: "github-actions[bot]"
          GIT_COMMITTER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
        shell: bash
        run: |
          set -e
          NEW="f/$(python3 - <<'PY'
import secrets; print(secrets.token_hex(6)+".mp3")
PY
)"
          echo "New file: $NEW"
          # xóa tất cả mp3 cũ trong f/
          git rm -f f/*.mp3 2>/dev/null || true
          mv fetched.mp3 "$NEW"
          echo "$NEW" > f/current.txt

          git config user.name "$GIT_COMMITTER_NAME"
          git config user.email "$GIT_COMMITTER_EMAIL"
          git add -A
          git commit -m "Fetch & rotate -> $NEW" || echo "No changes"
          git push

      - name: Output new URL
        shell: bash
        run: |
          REPO="${{ github.repository }}"
          USER="${REPO%%/*}"
          NAME="${REPO##*/}"
          CUR=$(cat f/current.txt)
          echo "✅ File mới: $CUR"
          echo "➡️ URL: https://$USER.github.io/$NAME/$CUR"
